language: php
services:
- memcached
php:
- 7.0
- hhvm
env:
  - DB=mysql                         # only database tests against mysql
  - DB=sqlite    # only database tests against postgresql
  - DB=pgsql
addons:
  postgresql: "9.3"
before_install:
  - apt-get update -qq -y
  - apt-get install -y mysql-utilities
install:
  - phpenv rehash
  - travis_retry composer require "satooshi/php-coveralls" "^1" --no-update --dev
  - travis_retry composer install
before_script:
  - echo $TRAVIS_PHP_VERSION
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo 'date.timezone = "Asia/Taipei"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini ; fi
  # - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # phpenv config-add doesn't work
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add travis/php.ini ; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database testing;" -U postgres ; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot -e "create database testing charset utf8;" ; fi
  - cp -v db/config/database.travis-ci.yml db/config/database.yml
  - bin/maghead use -f db/config/database.yml
  # - php bin/maghead db create -D=$DB
  - bin/maghead schema build -f
  - bin/maghead schema build Maghead\\Model\\MetadataSchema
  - bin/maghead schema build -f src # build meta model class
  - bin/maghead sql --rebuild -D=$DB
script:
  - phpunit --version
  - phpunit --debug -c phpunit.xml.dist
after_success:
  - php vendor/bin/coveralls -v
matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
# matrix:
#   exclude:
#     - php: hhvm
#       env: DB=pgsql DB_USER=postgres DB_NAME=postgres  # driver currently unsupported by HHVM
#     - php: hhvm
#       env: DB=sqlite # some issues at the moment
cache:
  apt: true
  directories:
  - vendor
  - $HOME/.composer/cache
