dist: trusty
language: php
services:
- memcached
- mongodb
- postgresql
- mysql
addons:
  apt:
    packages:
    - gearman-job-server
    - libgearman-dev
    - gearman-tools
php:
- '7.0'
- '7.1'
- hhvm
env:
- DB=mysql
- DB=sqlite
- DB=pgsql
matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
  - php: '7.0'
before_install:
- if [[ "$DB" == "mysql" ]]; then sudo sh travis/install-mysql-utilities ; fi
install:
- phpenv rehash
- "./travis/setup-php"
- travis_retry composer install
before_script:
- "./travis/setup-db"
- bin/maghead use -f tests/config/$DB.yml
- bin/maghead schema build -f
script:
- travis/run-phpunit
- travis/run-examples
before_cache:
- travis_retry composer require "satooshi/php-coveralls" "~1"
after_success:
- if [[ "$DB" == "mysql" ]]; then php vendor/bin/coveralls -v ; fi
cache:
  apt: true
  directories:
  - vendor
  - exts
  - "$HOME/.composer/cache"
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: QJC3hb9lJ0aCMI3VcTnOBOUgFp/CXEoUP8pToD/lMrOvlRBv9CS3hOUKQZVtymtI5ocVnPo5gXGf8CBXrTJ2ZLP8E7VaIn/zE1S1BbmKOLVPtyof5ayFE8v3AptV7rPNn3db1Se+G73aTYdx26NergfeO5qmu6fLYxrlyAebjFU=
