# sudo: required
dist: trusty

language: php
services:
- memcached
- mongodb
- postgresql
- mysql


addons:
  apt:
    packages:
    - gearman-job-server
    - libgearman-dev
    - gearman-tools

php:
- "7.0"
- "7.1"
# - hhvm
env:
  - DB=mysql     # mysql database tests only
  - DB=sqlite    # pgsql database tests only
  - DB=pgsql
matrix:
  fast_finish: true
  allow_failures:
  - php: "hhvm"
  - php: "7.1"



before_install:
- if [[ "$DB" == "mysql" ]]; then sudo sh travis/install-mysql-utilities ; fi



install:
- phpenv rehash
- ./travis/setup-php
- travis_retry composer install
before_script:
  - "rm -rf *.sqlite"
  - if [[ "$DB" == "pgsql" ]]; then ./travis/setup-pgsql ; fi
  - if [[ "$DB" == "mysql" ]]; then ./travis/setup-mysql ; fi
  - bin/maghead use -f tests/config/$DB.yml
  # - php bin/maghead db create -D=master
  - bin/maghead schema build -f
  - bin/maghead sql --rebuild master
script:
- travis/run-phpunit
- travis/run-examples
before_cache:
- travis_retry composer require "satooshi/php-coveralls" "~1"
after_success:
- if [[ "$DB" == "mysql" ]]; then php vendor/bin/coveralls -v ; fi
# matrix:
#   exclude:
#     - php: hhvm
#       env: DB=pgsql DB_USER=postgres DB_NAME=postgres  # driver currently unsupported by HHVM
#     - php: hhvm
#       env: DB=sqlite # some issues at the moment
cache:
  apt: true
  directories:
  - vendor
  - $HOME/.composer/cache
notifications:
  email:
    on_failure: change
