language: php
services:
- memcached
php:
- "7.0"
- "7.1"
# - hhvm
env:
  - DB=mysql     # mysql database tests only
  - DB=sqlite    # pgsql database tests only
  - DB=pgsql
matrix:
  fast_finish: true
  allow_failures:
  - php: "hhvm"
  - php: "7.1"
addons:
  postgresql: "9.3"
before_install:
- if [[ "$DB" == "mysql" ]]; then sudo sh travis/install-mysql-utilities ; fi
install:
- phpenv rehash
- travis_retry composer require "satooshi/php-coveralls" "~1" --no-update
- travis_retry composer install
before_script:
  - echo $TRAVIS_PHP_VERSION
  # - phpenv config-rm xdebug.ini
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo 'date.timezone = "Asia/Taipei"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini ; fi
  # - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # phpenv config-add doesn't work
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add travis/php.ini ; fi
  - if [[ "$DB" == "pgsql" ]]; then ./travis/setup-pgsql ; fi
  - if [[ "$DB" == "mysql" ]]; then ./travis/setup-mysql ; fi
  - bin/maghead use -f tests/config/$DB.yml
  # - php bin/maghead db create -D=master
  - bin/maghead schema build -f
  - bin/maghead schema build Maghead\\Model\\MetadataSchema
  - bin/maghead schema build -f src # build meta model class
  - bin/maghead sql --rebuild -D=master
script:
- phpunit --version
- phpunit --debug --configuration phpunit.xml.dist
after_success:
- php vendor/bin/coveralls -v
# matrix:
#   exclude:
#     - php: hhvm
#       env: DB=pgsql DB_USER=postgres DB_NAME=postgres  # driver currently unsupported by HHVM
#     - php: hhvm
#       env: DB=sqlite # some issues at the moment
cache:
  apt: true
  directories:
  - vendor
  - $HOME/.composer/cache
