---
cli:
  bootstrap: tests/bootstrap.php
schema:
  auto_id: true
  base_record: \Maghead\Runtime\Record
  base_collection: \Maghead\Runtime\Collection
  paths:
  - tests
instance:
  local:
    dsn: 'mysql:host=localhost'
    user: root
databases:
  master:
    dsn: 'sqlite::memory:'
    query_options: { quote_column: true, quote_table: true }
  mysql:
    dsn: 'mysql:host=localhost;dbname=testing'
    user: root
    # create database testing charset utf8;
    # grant all privileges on testing.* to testing@localhost identified by 'testing';
  pgsql:
    dsn: 'pgsql:host=localhost;dbname=testing'
    user: postgres
