---
schema:
  auto_id:
    name: id
    class: \Maghead\Schema\Column\UUIDPrimaryKeyColumn
  # customize your schema paths
  paths:
    - src/
databases:
  master:
    driver: mysql
    database: todos
    user: root
    # slave:
    #   dsn: 'mysql:host=localhost;dbname=test'
    #   user: root
    #  pass: 123123
